name: Checks

on:
  pull_request:
    branches: [main]

#  Notice the dockerhub vars match what we created in GitHub variables for the repo.
jobs:
  test-lint:
    name: Test and Lint
    uses: ./.github/workflows/test-and-lint.yml
    secrets:
      DOCKERHUB_USER: ${{vars.DOCKERHUB_USER}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
